CREATE DATABASE UNIVERSIDADE;

USE UNIVERSIDADE;

CREATE TABLE ENDERECO(
	END_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    END_LOGRADOURO VARCHAR(120) NOT NULL,
    END_BAIRRO VARCHAR(50) NOT NULL,
    END_COMPLEMENTO VARCHAR(50)
);

CREATE TABLE CURSO(
	CUR_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(30) NOT NULL,
    DURACAO_ANOS INT NOT NULL
);

CREATE TABLE ALUNO(
	ALU_RA INT(7) NOT NULL UNIQUE PRIMARY KEY,
    NOME VARCHAR(45) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL UNIQUE,
    TELEFONE VARCHAR(9) NOT NULL,
    ALU_DT_DELECAO_DATE DATE,
    CUR_ID INT NOT NULL,
    END_ID INT NOT NULL,
    CONSTRAINT FK_ALUNO_CURSO FOREIGN KEY(CUR_ID) REFERENCES CURSO(CUR_ID),
    CONSTRAINT FK_ALUNO_ENDERECO FOREIGN KEY(END_ID) REFERENCES ENDERECO(END_ID)
);

CREATE TABLE PROFESSOR(
	PRO_RA INTEGER(7) NOT NULL UNIQUE PRIMARY KEY,
    PRO_NOME VARCHAR(45) NOT NULL,
    PRO_TELEFONE VARCHAR(11) NOT NULL,
    PRO_EMAIL VARCHAR(50) NOT NULL,
    PRO_DT_DELECAO_DATE DATE,
    END_ID INT NOT NULL,
    CONSTRAINT FK_PROFESSOR_ENDERECO FOREIGN KEY(END_ID) REFERENCES ENDERECO(END_ID)
);

CREATE TABLE DISCIPLINA(
	DIS_ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    DIS_NOME VARCHAR(30) NOT NULL,
    PRO_RA INTEGER(7) NOT NULL,
    CONSTRAINT FK_DISCIPLINA_PROFESSOR FOREIGN KEY(PRO_RA) REFERENCES PROFESSOR(PRO_RA)
);

CREATE TABLE GRADE(
	GRA_ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    GRA_SEMESTRE INT(1) NOT NULL,
    GRA_ANO INT(4) NOT NULL,
    CUR_ID INTEGER NOT NULL,
    CONSTRAINT FK_GRADE_CURSO FOREIGN KEY(CUR_ID) REFERENCES CURSO(CUR_ID)
);

CREATE TABLE GRADE_DISCIPLINA(
	GRD_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    GRD_CARGA_HORARIA TIME NOT NULL,
    DIS_ID INT NOT NULL,
    GRA_ID INT NOT NULL,
    CONSTRAINT FK_GRADE_DISCIPLINA_DISCIPLINA FOREIGN KEY(DIS_ID) REFERENCES DISCIPLINA(DIS_ID),
    CONSTRAINT FK_GRADE_DISCIPLINA_GRADE FOREIGN KEY(GRA_ID) REFERENCES GRADE(GRA_ID)
);

CREATE TABLE PROFESSOR_CURSO(
	PRC_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    PRO_RA INT(7) NOT NULL,
    CUR_ID INT NOT NULL,
    CONSTRAINT FK_PROFESSOR_CURSO_PROFESSOR FOREIGN KEY(PRO_RA) REFERENCES PROFESSOR(PRO_RA),
    CONSTRAINT FK_PROFESSOR_CURSO_CURSO FOREIGN KEY(CUR_ID) REFERENCES CURSO(CUR_ID)
);

CREATE TABLE ATIVIDADE_COMPLEMENTAR(
	ATC_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    ATC_DESCRICAO VARCHAR(128) NOT NULL,
    ATC_HORAS_TOTAIS TIME NOT NULL,
    GRA_ID INT NOT NULL,
    CONSTRAINT FK_ATIVIDADE_COMPLEMENTAR_GRADE FOREIGN KEY(GRA_ID) REFERENCES GRADE(GRA_ID)
);

CREATE TABLE ATIVIDADE_ALUNO(
	ATA_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    ATA_HORAS_ENTREGUES TIME NOT NULL,
    ATC_ID INT NOT NULL,
    ALU_RA INT(7) NOT NULL,
    CONSTRAINT FK_ATIVIDADE_ALUNO_ATIVIDADE FOREIGN KEY(ATC_ID) REFERENCES ATIVIDADE_COMPLEMENTAR(ATC_ID),
    CONSTRAINT FK_ATIVIADE_ALUNO_ALUNO FOREIGN KEY(ALU_RA) REFERENCES ALUNO(ALU_RA)
);

CREATE TABLE LOGIN(
	LOG_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    LOG_SENHA VARCHAR(256) NOT NULL,
    LOG_ATIVO BOOL NOT NULL,
    ALU_RA INT(7),
    PRO_RA INT(7),
    CONSTRAINT FK_LOGIN_ALUNO FOREIGN KEY(ALU_RA) REFERENCES ALUNO(ALU_RA),
    CONSTRAINT FK_LOGIN_PROFESSOR FOREIGN KEY(PRO_RA) REFERENCES PROFESSOR(PRO_RA)
);
